$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: <environment-name>
#image: mcr.microsoft.com/azureml/minimal-ubuntu18.04-py37-cuda11.0.3-gpu-inference:latest
image: mcr.microsoft.com/azureml/minimal-ubuntu18.04-py37-cpu-inference:latest
conda_file: webservice-conda.yml
